### ISSUE TITLE
Error : Job not found

### ISSUE THREAD

**Issue by sawhneygunjan** [jenkinsci/coordinator-plugin#10]
Getting this error 

Atomic Job: Testing not found
Atomic Job: Testing-2 not found
Build step 'Coordinator' marked build as failure
Finished: FAILURES

But both the jobs exist

**Comment by ace-han** [comment]
@sawhneygunjan Please ensure no special tokens in job name `Testing` and `Testing-2`. Any spaces heading, tailing, in-between?

Please zip  entire `$JENKINS_HOME/jobs` folder or package the small portials and send to ace.jl.han@gmail.com for my detail checing, thx.

**Comment by ace-han** [comment]
@sawhneygunjan I think you probably no job definition for job `Testing` and `Testing-2`. I will close this issue. I will add a more specific doc about how to use this plugin later, thx.
