### ISSUE TITLE
reading parameters from parent job

### ISSUE THREAD

**Issue by Gabbyr** [jenkinsci/coordinator-plugin#15]
I was trying to pass parameters to a child job within coordinator but failed. somehow it doesn't get into the child job I am trying to run. it's a simple environment variable. am I missing something here ?

**Comment by ace-han** [comment]
Hello there,

Plz make sure the parameter `type` and `name` are exact the same type in parent (coordinator-job) job and child job. Hope this could hope you out

**Comment by Gabbyr** [comment]
hi - the name is the same but the types are different. however, I use it in a string context on the child job so it can't be the same. I solved it with files reading/writing for now.

**Comment by ace-han** [comment]
Grad that you figured it out !

**Comment by Gabbyr** [comment]
Hi, I have sent you some feedback and wishful things some time ago. got a
chance to have a look maybe. ?

**Comment by ace-han** [comment]
@Gabbyr Maybe I've lost it in my mailbox, would be nice if you can resend it or just directly paste your requirement as a feature request in Github.

Thx for your trying out this plugin
