### ISSUE TITLE
Coordinator Parameters not correctly shown after a build is launched

### ISSUE THREAD

**Issue by Max-Serra** [jenkinsci/coordinator-plugin#17]
Hi Jindi and Ace,

I was very happy to find and try latest 1.1.1 version which solved Parameters tab issues. Unfortunately I'm using two not standard Job Parameters plug ins discovering further issues:  Parameters Separator (https://wiki.jenkins-ci.org/display/JENKINS/Parameter+Separator+Plugin) and Active Choices (https://wiki.jenkins-ci.org/display/JENKINS/Active+Choices+Plugin). 

I prepared two sample jobs that you could try in order to reproduce the issues: coordinator_active_choice_reactive_parameter and added in it,  active_choice_reactive_parameter. I'm attaching the jobs folders that you could include in your own jenkins instance, hopefully inheriting also the Build History.
[coordinator_active_choice_reactive_parameter.zip](https://github.com/jenkinsci/coordinator-plugin/files/66455/coordinator_active_choice_reactive_parameter.zip)
[active_choice_reactive_parameter.zip](https://github.com/jenkinsci/coordinator-plugin/files/66456/active_choice_reactive_parameter.zip)

I've prepared as well some screenshots:

![parametersbeforerun](https://cloud.githubusercontent.com/assets/16347984/11894466/b3a6818e-a577-11e5-87eb-c89e0838cdf8.png)

In the picture above, there are both types of not standard parameters. Adding more than one Parameters Separators, once the build is launched the following is how the Parameters tab is shown.

![parametersafterrun](https://cloud.githubusercontent.com/assets/16347984/11894475/c17a2fd6-a577-11e5-84c7-2ea61c12e74d.png)

So this issue is big because the whole tab content is lost.

Removing Parameter Separators, the tab is shown again, but there is still an issue now linked to Active Choice Reactive Parameters. As you see I created a custom and dynamic parameter which allow to add and fill html table rows. By that plug in is possible to store the values inserted in the fields and the output is put in a json structure.

The issue is that once the job is launched, in the historical build perspective and even earlier during the run,  the parameter is shown as its default (see following)
![parameterstableasdefault](https://cloud.githubusercontent.com/assets/16347984/11894758/a4ecf40a-a579-11e5-9365-e5df4233ab8a.png)

and not shown as in a standard job , so showing the json structure, as below:

![parametersinsertedasjson](https://cloud.githubusercontent.com/assets/16347984/11894766/b449476e-a579-11e5-8c36-aaba201530ce.png)

I hope I gave you enough information.

Max

**Comment by ace-han** [comment]
Sorry for the late reply, I will look into it these days

**Comment by ace-han** [comment]
@Max-Serra for your case
> the parameter is shown as its default

I don't think I could make it.  It's way beyond that I could hack it. 

I debugged into it. The `Active Choices Plugin` instance in your case is actually [DynamicReferenceParameter](https://github.com/jenkinsci/active-choices-plugin/blob/master/src/main/java/org/biouno/unochoice/DynamicReferenceParameter.java)



and it does not override a special method from standard `hudson.model.ParameterDefinition` and I could not find an easy work-around to get it displayed in the correct form of HTML with value, nor get an demo on how it original displays with value in HTML(because it `Active Choices Plugin` is not written by me...)

I think you could request the author of `Active Choices Plugin` to implement the standard interface
```java
    /**
     * Create a new instance of this parameter definition and use the passed
     * parameter value as the default value.
     *
     * @since 1.405
     */
    public ParameterDefinition copyWithDefaultValue(ParameterValue defaultValue) {
        // By default, just return this again
        return this;
    }
```

and for seperator situation I still need more digging but I think it's more achievable.

**Comment by Max-Serra** [comment]
Hi Ace,

Thanks for starting the issues analysis. I was on Christmas Holidays, that's the why of my late reply too. 

Any news regarding Separator Parameter issue? In our Coordinator Job we put only one separator as first parameter in order to show the Parameter tab , but in this case even String Parameters don't work correctly showing the default values instead of the current ones. 

So it seems that putting more than one separator causes the issue of the whole content of Parameters tab not shown  (as described in the first comment). Putting only one separator at the beginning causes the fault described in this comment.

**Comment by ace-han** [comment]
@Max-Serra , I've located the problem. But still need sometime to do the fix
In a word, there is a list out of range bug triggered while displaying parameters with Separator Parameter

as below:
![issue17](https://cloud.githubusercontent.com/assets/1177332/12300072/cc3fc79a-ba54-11e5-9f5a-70d7f288a6e5.jpg)

**Comment by ace-han** [comment]
@Max-Serra There are some considerations that I won't officially support `parameter-separator-plugin` issue.
It will jeopardy a lot of history page displaying logic in `coordinator-plugin`.

1. Fix from `parameter-separator-plugin`. Using the new code pull request in jenkinsci/parameter-separator-plugin#5, plz choose one of the belows at your desire
    * Download this compiled one I've done for you [parameter-separator.zip](https://github.com/jenkinsci/coordinator-plugin/files/93328/parameter-separator.zip)
    * Wait for the author to merge and upgrade `parameter-separator-plugin` in your jenkins
    * Compile the hpi yourself by `mvn package` with the code in jenkinsci/parameter-separator-plugin#5, then upgrade with the compiled hpi file
2. Partial fix from `coordinator-plugin`.
    * Download this compiled one I've done for you [coordinator-1.2.0-SNAPSHOT.hpi.zip](https://github.com/jenkinsci/coordinator-plugin/files/93319/coordinator-1.2.0-SNAPSHOT.hpi.zip)
    * Checkout the code in this commit 06d577c, and then `mvn package`, then upgrade with the compiled hpi file

* every manual plugin upgrade with hpi file, go to page `http://your_domain:port/pluginManager/advanced` like below
![image](https://cloud.githubusercontent.com/assets/1177332/12377119/bd2be9c8-bd4c-11e5-93f6-5a8aef53e40e.png)
*  with Option 2, you will get `parameter-separator-plugin` NOT BEING DISPLAYED as I mentioned above it will jeopardy a lot of history page displaying logic

Using Option 2 will get below embarrassing situation
Showing parameters in build page
![image](https://cloud.githubusercontent.com/assets/1177332/12377107/14c980b0-bd4c-11e5-8bdd-8d56604127c0.png)

Showing parameters in histories page(NOT showing  `parameter-separator-plugin` ones )
![image](https://cloud.githubusercontent.com/assets/1177332/12377113/5400153c-bd4c-11e5-9dcf-17726ece61db.png)

So Option 1 is my recommendation.

Let me know if these solutions work fine for you.

**Comment by Max-Serra** [comment]
Hi Ace, 
if it is more robust I agree to adopt the first solution (I'll try to use the zipped hpi containing the fix, many thanks for providing it: i'll let you know asap). By your analysis it seems that the compatibility of such customized parameter plug-in with Coordinator, depends a lot by a correct standardization. The Parameter tab of the Coordinator I think it is a crucial feature for a good usability. However since the Parameter Tab and the Coordinator job are able to automatically include not standard parameters and override them, Jenkins should provide a standard interface which should be implemented by all the parameters types and finally considered also by Coordinator.

The Coordinator project is working in the same way as the Freestyle project, for the parameters. So if in a Jenkins instance have been installed several parameters plug-ins, the Freestyle project will see them and in some way there  is a compatibility check to verify if those plugins are compatible.
Of course Freestyle project is by default provided by Jenkins, so the plug-ins are forced to be compliant by default as well (there is also a check between plug-ins and Jenkins versions as well).

The Coordinator project isn't built-in, so to work with all possible parameters plug-ins, it requires an interaction with those projects, but that cannot be satisfied by default unfortunately. I guess that the Coordinator project  could handle this issue, first of all simply writing in the related wiki page, that the parameters seen, correctly handled by it and surely supported are those built-in in Jenkins (plus a set of customized ones, if tested or involved in the maintenance, declaring names and possibly versions). Another a bit more complicated solution could be to implement a filtering mechanism inside the code, then the Coordinator project will show only parameters compatible, by default the ones built-in in Jenkins , plus the ones tested or aligned thanks to a community effort (which seems needed to make compliant the Active Choices Plugin as well ). The best could be to use both solutions.

Which is your opinion Ace?

**Comment by kymair** [comment]
@Max-Serra Though it is not totally impossible to filter imcompatible plugins, the implementation can be tricky and ugly. Given the current adoption of Coordinator, I think a "known issues" wiki page is a better option. 

By the way, we can add you as the project contributor as well, if you are interested :-) Believe you can write better documents than us.

**Comment by Max-Serra** [comment]
@kymair I agree, your choice is reasonable.

Regarding your proposal, yes I'm interested, thank you. For sure currently I would like to participate to the testing side, even if I'm more a designer/architect.

Let's see if I will can contribute to the development as well, since I didn't ever implemented a Jenkins plug-in. For sure I will start setting up a Jenkins plug-in development environment in order to be able to debug Coordinator project, and hopefully helping you much more in addressing the issues eventually found.

**Comment by ace-han** [comment]
Adding @Max-Serra to the project and issue closed
