### ISSUE TITLE
any restrictions on which jobs can be run through coordinator ?

### ISSUE THREAD

**Issue by Gabbyr** [jenkinsci/coordinator-plugin#18]
i am having an issue with jobs that just won't run via coordinator but i couldn't find the common denominator between them all. 
is there any limitation regarding the jobs which i can/can't run in s or p mode ?

**Comment by ace-han** [comment]
@Gabbyr The answer is No.

The design for this plugin is to take control over other jobs. 

If you find any restriction then I think it's coordinator job within a coordinator job. And I won't support that cuz I don't have any idea about how the ui should be displayed in this situation, it's quite nasty.

For your case
1. Look through the jenkins log every time the failing coordinator job triggered, see if any exception throws
2. Zip the relevant `jobs` folder under your jenkins folder, I will run a quick check for you. like `~/win7e/workspace/github/jee/coordinator-plugin/work/jobs`
![image](https://cloud.githubusercontent.com/assets/1177332/12381726/d4896ce8-bdca-11e5-8e02-669f62f3c925.png)

**Comment by Gabbyr** [comment]
Thanks,I will follow your guidance here. my problem is that the coordinator
job just hangs in there and not running the requested job which includes
another job indeed, but not a coordinator one. It just runs another job
with some parameters. Is that a problem as well ?

**Comment by ace-han** [comment]
Plz make sure the you've got enough executor as well. 

`coordinator` would take up one executor, like below

![image](https://cloud.githubusercontent.com/assets/1177332/12384102/45b3ff3c-bde9-11e5-9425-1a3a01d1ef93.png)

**Comment by Gabbyr** [comment]
Yes,I do have,since when tried running other jobs,it worked. i am guessing
it has to do with a job inside another job,but I am not sure yet.

**Comment by Gabbyr** [comment]
hi - I'll try to show you what is it that we get now. i don't if it's
related to multi job type maybe, or anything else, but we fail to run the
following :

[image: Inline image 1]

and we see this on the build page :

[image: Inline image 2]

if we change the order of builds for the S jobs, we get the error on the
other one.
the jobs are simple and includes only bash calls and such, not something
unusual.

the parallel job runs ok.

Thanks,

Gabby.

**Comment by Gabbyr** [comment]
Ace - another quick one - if you define a job as S one, does it mean that
if you 2 serial jobs and the first one fails, the other won't run at all ?

Thanks.

**Comment by ace-han** [comment]
@Gabbyr Yes.

The direct children jobs under `S` one will get serial run one by one 

If the leading job fails then its siblings(which is sharing the same `S` parent) wont get run at all

**Comment by Gabbyr** [comment]
Thanks Ace. and currently there is no way to put logic there, right ?

**Comment by ace-han** [comment]
@Gabbyr No. Currently not supported.

I dont wanna be involved with that kind of complicated scenarios.

If that is the case, you may consider `Jenkins` native build trigger.

And is it okay for me to close this issue now?

**Comment by Gabbyr** [comment]
Yes,sure.
i just didn't get an answer from you regarding a regular nested jobs - that
should work as usual or it's not supported just like a coordinator job
inside a coordinator job ?

**Comment by ace-han** [comment]
@Gabbyr From your [comment](https://github.com/jenkinsci/coordinator-plugin/issues/18#issuecomment-172814511), the demo images are broken on github, plz update that comment so I could see what you are referring to.

**Comment by ace-han** [comment]
closing this issue after 7 days no replies
@Gabbyr I think the answer to your question is no

**Comment by Gabbyr** [comment]
Hi Ace - i am running now Jenkins version 1.642.1. when I try to run a
coordinator job now, I don't see the Job UI, only an empty white area. do
you know if the security changes made at this jenkins version are causing
this ?

Thanks,

Gabby.

**Comment by ace-han** [comment]
Plz refer to #20, and do not raise new issue on the closed one
Thx.

**Comment by Gabbyr** [comment]
Thanks Ace.
