### ISSUE TITLE
CloudBees CI failed due to unrecognized param -Xdoclint:none for maven-javadoc-plugin  

### ISSUE THREAD

**Issue by kymair** [jenkinsci/coordinator-plugin#21]
CloudBees CI uses JDK1.7 and it doesn't recognize `-Xdoclint:none`

    [ERROR] Exit code: 1 - javadoc: error - invalid flag: -Xdoclint:none
    [ERROR] Command line was: /opt/java/sdk/Oracle/x86_64/jdk1.7.0_79/jre/../bin/javadoc @options @packages

Need figure out a way to cater for JDK8 and earlier versions at the same time.
https://jenkins.ci.cloudbees.com/job/plugins/job/coordinator-plugin/31/console

**Comment by ace-han** [comment]
1. drop

**Comment by ace-han** [comment]
We have following options:

1. drop this plugin directly since we do really use it
2. profile activation by jdk version, referring to http://stackoverflow.com/questions/15886209/maven-is-not-working-in-java-8-when-javadoc-tags-are-incomplete
