### ISSUE TITLE
Possible enhancement for serial jobs

### ISSUE THREAD

**Issue by Max-Serra** [jenkinsci/coordinator-plugin#22]
Hi Guys,

As you know in my team we are using Coordinator more for Test Automation than to Build and/or to Deploy code.  I Read some comments in this post  [any restrictions on which jobs can be run through coordinator ?](https://github.com/jenkinsci/coordinator-plugin/issues/18) where Gabbyr mentioned something regarding the behavior of the jobs under S branch. I read as well in the wiki the paradigm behind the branches in S and P mode.

Anyway there are cases, especially when the atomic jobs are set to run test cases, where it's needed to run them in a serial branch but without stopping the execution in case of jobs failures (Feature/Integration/System tests). 

If the Coordinator could add just a field in order to set if the job is blocking or not in S, this could increase very much the usability of the plugin. This feature is making the difference in its adoption as a sort of GUI Test Manager.

Do you think this could be feasible? Could you consider to add this option? 

Max

**Comment by ace-han** [comment]
@Max-Serra and @Gabbyr We will consider this in the future release.

We will add one option named `blocking or non-blocking` while configuring the execution plan in page `/jobs/xxx/configure`

```sh
blocking-Root-S
|--non-blocking-S_1
|     |__leaf_sa
|--non-blocking-P_2
|     |--leaf_pa
|     |__leaf_pb
|__leaf_3
|__blocking-P_4
      |--leaf_pc
      |__leaf_pd
```

In above case, any of `S_1`, `P_2`, `leaf_3` fails won't break the whole build

However, we could really need some idea about how to present these `blocking` or `non-blocking` information in the ui presentation while doing configuration. 

Any thought?

**Comment by Max-Serra** [comment]
It sounds very good. Let me think a bit, I'll collect some feedbacks and I'll be back with some ideas. How can we help you in testing? Which branch are you going to push? 

We have complex setups with jenkins slaves and several configurations.

**Comment by ace-han** [comment]
Update `blocking` to `breaking` for much clearer intention

@Max-Serra We first need upgrade the `jquery`, `jstree` library. 
In the mean time, you could collect some ideas about this feature.

For git branching, we will follow [git flow model](http://nvie.com/posts/a-successful-git-branching-model/). The branch for this feature `feature/breaking_option` will be pushed after [feature/jstree_upgrade](https://github.com/jenkinsci/coordinator-plugin/commits/feature/jstree_upgrade) is accomplished

And it will be a great help if you can help on writing some test cases for this plugin since this plugin has no test at all for the time being

**Comment by Max-Serra** [comment]
Hi Ace,

I'm back with a very simple idea. I reused a bit the icons within Coordinator plug-in. I guess we could change the node icons, using a red octagon for the breaking serial (as the stop traffic sign), and changing just the colors for the non-breaking serial and parallel nodes. I attach here the icons modified.

![red-octagon-serial-breaking](https://cloud.githubusercontent.com/assets/16347984/14013450/ea6f296a-f1ac-11e5-9d83-7fee2b10240f.png)
![coordinator-serial-non-breaking](https://cloud.githubusercontent.com/assets/16347984/14013478/00ccea26-f1ad-11e5-9d9c-718efc8876a4.png)
![coordinator-parallel-non-breaking](https://cloud.githubusercontent.com/assets/16347984/14013480/0379771c-f1ad-11e5-838e-7c9e48775811.png)

By this way it should be clear which are breaking nodes and non-breaking nodes. Below how the Gui could look like:

![coordinator_plan](https://cloud.githubusercontent.com/assets/16347984/14013529/3a7b5410-f1ad-11e5-89cd-187625e45c58.png)
![coordinator-tree2](https://cloud.githubusercontent.com/assets/16347984/14013535/3fbbb32a-f1ad-11e5-9aef-5cbdf97f5352.png)

What do you think?

**Comment by ace-han** [comment]
@Max-Serra please help test with the latest code, thx.

**Comment by Max-Serra** [comment]
Hi Ace, very good. I will install this beta version of the plugin on a Jenkins dev instance cloned by the production one. The configuration of the Execution Plan looks like the following:

![regressiontree](https://cloud.githubusercontent.com/assets/16347984/14274149/d8ea9e42-fb0f-11e5-844c-f3457f08c1ed.png)


The tree above runs jobs over both linux and windows envs, having master-slaves setup. So I guess it's a good test bench for the plugin (using Jenkins 1.631...**the latest stable one is causing problems in the Coordinator History visualization**).

I'll let you know asap.

**Comment by ace-han** [comment]
Hi, @Max-Serra for any issue relevant to this feature plz submit a new issue to avoid this conversation list becoming way too long.

Regarding to history display issue in histories page plz share more details, a screen shot would be better

**Comment by Max-Serra** [comment]
Ok, you are right, this issue is marked closed.
