### ISSUE TITLE
When Security is Enabled the Jobs included in the Plan are not found during the Execution

### ISSUE THREAD

**Issue by Max-Serra** [jenkinsci/coordinator-plugin#29]
Hi,

I've enabled the security by the Configure Global Security page, setting up LDAP option and Project-based Matrix Authorization Strategy. 

**Some details:**

Jenkins version 1.631
Coordinator plugin versions: 1.1.1 and 1.2.0-SNAPSHOT (pulled from develop branch)

**Scenario 1 with Failure:**

- Logged as Administrator using my credentials 

- cloned some old jobs created previously as anonymous 

- the Execution Plan looks like the following:

![planfailedonceloggedasadministrator](https://cloud.githubusercontent.com/assets/16347984/14309170/0e34e514-fbdb-11e5-9ad1-3bb84e5dd5bf.jpg)

- Building the Execution Plan, which is really simple (running locally on the master), the output is the following:

Started by user Massimiliano Serra
[EnvInject] - Loading node environment variables.
Building on master in workspace /jenkins/jobs/coordinator_active_choice_reactive_parameter_2/workspace
Atomic Job: active_choice_reactive_parameter_2 not found
Build step 'Coordinator' marked build as failure
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

**Scenario 2 with success**:

- set Anonymous user as Administrator

- logged as Anonymous

- running the same Execution Plan now the job is correctly found and executed as shown in the following output:

Started by user anonymous
[EnvInject] - Loading node environment variables.
Building on master in workspace /jenkins/jobs/coordinator_active_choice_reactive_parameter_2/workspace
Atomic Job ( active_choice_reactive_parameter_2 ) Triggered
Atomic Job: active_choice_reactive_parameter_2  # 2 Completed, Result: SUCCESS
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: SUCCESS

**Scenario 3 with success:**

- set Anonymous user as Administrator

- logged using now my credentials

- running the same Execution Plan now the result is as in the Scenario 2 

**Scenario 4 failed again:**

- set Anonymous user with enabled only the option "Overall->Read" under the Matrix Authorization table

- logged using my credentials

- same result as Scenario 1

**Comment by ace-han** [comment]
Anyway, plz try it out with the latest code.

I believe this issue persists from the date this plugin pushed to `github`. 
It has nothing to do with the version of `jenkins`

Thx for raising it out. ^_^

**Comment by Max-Serra** [comment]
Very good Ace,

By the latest code the plan I mentioned above is now working. I'll try out with much more complex one.

Many thanks.

**Comment by Max-Serra** [comment]
Hi Ace,

I guess we can consider solved this issue. I executed the Coordinator job over a complex setup and it's working fine at the Security perspective and jobs triggering once a user is logged on.

**Comment by ace-han** [comment]
Good to know :muscle:
