### ISSUE TITLE
Overlapping content on build number page

### ISSUE THREAD

**Issue by darinpantley** [jenkinsci/coordinator-plugin#35]
The numbered build pages for my coordinator job do not look correct. For example, my `http://jenkins/job/my_coordinator_job/48` looks like this:

![tabs-absolute](https://cloud.githubusercontent.com/assets/5256138/15515678/05dc7c1a-21b5-11e6-9769-693ef0150391.png)

This is the HTML that isn't displaying correctly:
```
<div id="page-body" class="container-fluid">
   <div class="row">
        <div id="side-panel" class="col-sm-9 col-md-7 col-lg-6 col-xlg-4">
```

If I remove `"position: absolute;"` from `#side-panel` in `plugin/coordinator/css/tabs.css` then it renders correctly.

![tabs-no-absolute](https://cloud.githubusercontent.com/assets/5256138/15515680/086f3b48-21b5-11e6-9bc5-d81df60aaba8.png)

I haven't seen this problem with any other plugins. The main page for my coordinator job looks fine. Only the build number pages are showing incorrectly.

My environment:
- Firefox 46.0.1
- Jenkins 1.580.3
- Coordinator 1.2.0

**Comment by ace-han** [comment]
I believe it's related to this commit 91e691e8dce920232fc7e36f4cbf64c81e970760 due to this issue #20.
We will look into this lately along with other issues and group them in release 1.2.1

**Comment by ace-han** [comment]
@darinpantley, I went through the code in `pom.xml` and found that the minimum version `jenkins` is `1.596.1` which was greater than the version you listed. And I don't wanna be fancy about this css issue, using extra javascript.

My suggestion is that please upgrade your jenkins to version `>=1.596.1`
