### ISSUE TITLE
NPE when triggering Coordinator - PerformExecutor.java:137

### ISSUE THREAD

**Issue by brianjjoyce** [jenkinsci/coordinator-plugin#47]
I get the following error when attempting to trigger a Coordinator job from another job:

```
21:11:25 java.lang.NullPointerException
21:11:25 	at org.jenkinsci.plugins.coordinator.model.PerformExecutor.prepareExecutionPlan(PerformExecutor.java:137)
21:11:25 	at org.jenkinsci.plugins.coordinator.model.PerformExecutor.execute(PerformExecutor.java:74)
21:11:25 	at org.jenkinsci.plugins.coordinator.model.CoordinatorBuilder.perform(CoordinatorBuilder.java:58)
21:11:25 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
21:11:25 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
21:11:25 	at hudson.model.Build$BuildExecution.build(Build.java:205)
21:11:25 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
21:11:25 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
21:11:25 	at hudson.model.Run.execute(Run.java:1728)
21:11:25 	at hudson.model.Build.run(Build.java:113)
21:11:25 	at hudson.model.ResourceController.execute(ResourceController.java:98)
21:11:25 	at hudson.model.Executor.run(Executor.java:404)
21:11:25 Build step 'Coordinator' marked build as failure
```
looks like the #38 and #41 were reintroduced.

I have tried to work around it by setting the `executionPlan` in the triggering project and using the [Parameterized Trigger Plugin](http://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Trigger+Plugin) but then I get a ClassCastException:

```
20:59:38 java.lang.ClassCastException: hudson.model.StringParameterValue cannot be cast to org.jenkinsci.plugins.coordinator.model.CoordinatorParameterValue
20:59:38 	at org.jenkinsci.plugins.coordinator.model.CoordinatorBuild.getAction(CoordinatorBuild.java:299)
20:59:38 	at hudson.model.Build$BuildExecution.doRun(Build.java:151)
20:59:38 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
20:59:38 	at hudson.model.Run.execute(Run.java:1728)
20:59:38 	at hudson.model.Build.run(Build.java:113)
20:59:38 	at hudson.model.ResourceController.execute(ResourceController.java:98)
20:59:38 	at hudson.model.Executor.run(Executor.java:404)
20:59:38 Finished: FAILURE
```

I really want to get this Coordinator plugin to work so any and all assistance would be greatly appreciated.

Thanks
Brian

FYI - we are using Jenkins 2.32.1 and the latest version of the Coordinator 1.4.0

**Comment by kymair** [comment]
Hi, Brian

Thanks for using this plugin. I'm looking into the issue.

**Comment by kymair** [comment]
@brianjjoyce 

Hi, how did you trigger the coordinator job? By setting post-build action "Build other projects", or invoking via CLI, or something else?

**Comment by brianjjoyce** [comment]
Hi @kymair many thanks for your swift response and helping me with this - and fixing it :-) - awesome - it's much appreciated.

_> how did you trigger the coordinator job?_

Initially I triggered the Coordinator job from a git scm trigger, then I created a freestyle project that triggered it using 'Build other Projects', and finally I tried using the 'Trigger parameterized build on other projects' they all caused the NPE at PerformExecutor.java:137.

I then played around with parameters using 'Trigger parameterized build on other projects' but then got the ClassCastException detailed above.

Thanks again
Brian

BTW - When will do you think you be making a release with this fix?

**Comment by kymair** [comment]
@brianjjoyce I've packaged a snapshot version, please try whether it can work. Just rename coordinator-1.4.1-SNAPSHOT.zip to coordinator-1.4.1-SNAPSHOT.hpi and install.

[coordinator-1.4.1-SNAPSHOT.zip](https://github.com/jenkinsci/coordinator-plugin/files/767053/coordinator-1.4.1-SNAPSHOT.zip)

**Comment by brianjjoyce** [comment]
Hi @kymair - thanks for this - I will install and try the snapshot as soon as I can - there may be a delay before I can update our server - I will let you know if it fixes the issue.

Have a nice weekend.

Thanks 
Brian

**Comment by brianjjoyce** [comment]
Just wanted to let you know that the fix worked - thanks so much - it's great to see the Coordinator plugin doing it's thing :-)

@kymair  - thanks for the awesome support.

All the best
Brian

**Comment by kymair** [comment]
@brianjjoyce Glad to hear that!
Please feel free to create issue if you encounter any problem.
