### ISSUE TITLE
Jenkins version 2.289.4 issue with Coordination Plugin 

### ISSUE THREAD

**Issue by jbrunett** [jenkinsci/coordinator-plugin#53]
Using the Coordinator plugin in version Jenkins 2.289.4 when selecting the Build Now option the Build Execution Plan tab basically overlays the left side page options. The more options the harder to read the tab. Trying to determine if this issue is related to The Table to Div layout migration implemented in version 2.277.1.  Any help or insight would be appreciated.

![image](https://user-images.githubusercontent.com/34384930/123499485-d495e400-d5fc-11eb-9a28-77283a0fe33e.png)

**Comment by jbrunett** [comment]
that is version 2.289.1.

**Comment by jbrunett** [comment]
I was able to determine that everything after 2.237 version causes display issues in the coordinator plugin.  Not sure of functionality as the display issue makes the plugin hard to use.

**Comment by sakthi-dp2** [comment]
Thanks for update. 
Coordinator Plugin issue still not fixed?
We cant use other plugins like Testlog analyzer NGTestresults plugins if we get stuck at 2.237, any suggestions would be appreciated. Thanks in anticipation!

**Comment by Pietro28** [comment]
Hi, I experienced the same issue with Jenkins 2.319.1. Is there any plan to fix this incompatibility? 
Thanks in advance!

**Comment by sakthi-dp2** [comment]
Hi,
I am awaiting for this problem to be fixed, Unsure about the probability of fix.
Have you raised a defect ? I have nt do it so

**Comment by JamesAGrey** [comment]
I fixed this issue by updating line 4 of src/main/webapp/css/tabs.css (located at /var/lib/jenkins/plugins/coordinator/css/tabs.css in my instance):

Change:

#side-panel {
	position: absolute;
}

to:

#side-panel {
	position: relative;
}
