### ISSUE TITLE
Jenkins Coordinator Plugin does not work for Build with parameters option

### ISSUE THREAD

**Issue by sakthi-dp2** [jenkinsci/coordinator-plugin#54]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

<img width="960" alt="Jenkins_Coordinator_Plugin_Problem" src="https://user-images.githubusercontent.com/53250647/162104602-ce9a5464-ab19-4d92-8ad3-3db5bc65ca98.png">

### Reproduction steps

1.Install Coordinator Plugin for Jenkins on any platforms Like Windows, RHEL etc
2)Create a Coordinator parameterised Project
3)Go to the project and click build with parameters option
You will observe all GUI click options simply overylays to lefft side of the page.

There is an incompatibility between freestyle and Coordinator type of projects for BuildWithParameters option

### Expected Results

It should work as a free style project buildwithparameters option
<img width="960" alt="Jenkins_Freestyle_Project_working_copy" src="https://user-images.githubusercontent.com/53250647/162105088-dfbf75b7-6c05-4943-b409-f83fa30c9d6f.png">

### Actual Results

![Uploading Jenkins_Freestyle_Project_working_copy.png…]()

### Anything else?

may when i can i expect this problem solution.

**Comment by JamesAGrey** [comment]
I fixed this issue by updating line 4 of src/main/webapp/css/tabs.css (located at /var/lib/jenkins/plugins/coordinator/css/tabs.css in my instance):

Change:

#side-panel {
position: absolute;
}

to:

#side-panel {
position: relative;
}

**Comment by ace-han** [comment]
@JamesAGrey That's great! Please submit a PR

**Comment by JamesAGrey** [comment]
@ace-han PR submitted

**Comment by ace-han** [comment]
@JamesAGrey Well done! And I've already granted you with Write permission to this project. Thanks
