### ISSUE TITLE
Use matrix dashboard for task control and monitoring

### ISSUE THREAD

**Issue by samhe** [jenkinsci/coordinator-plugin#8]
Can change the dashboard style to matrix for task control and monitoring ? pls consider it.

**Comment by ace-han** [comment]
@samhe, could you be more specific? Since this plugin is now somehow displaying more like a matrix now, thx

![image](https://cloud.githubusercontent.com/assets/1177332/6772854/5f7a9a8c-d142-11e4-9ef6-56fcc2319222.png)

**Comment by ace-han** [comment]
No plan about it for the time being
